name: Sync GitHub Issue to Azure DevOps

on:
  issues:
    types: [opened, labeled, unlabeled, closed, reopened, edited]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  sync:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Determine ADO state from label
        id: setstate
        run: |
          echo "Label: ${{ github.event.label.name }}"
          LABEL="${{ github.event.label.name }}"
          if [[ "$LABEL" == "To Do" ]]; then
            echo "state=To Do" >> $GITHUB_OUTPUT
          elif [[ "$LABEL" == "In Progress" ]]; then
            echo "state=Doing" >> $GITHUB_OUTPUT
          elif [[ "$LABEL" == "Done" ]]; then
            echo "state=Done" >> $GITHUB_OUTPUT
          else
            echo "state=" >> $GITHUB_OUTPUT
          fi

      - name: Sync to Azure DevOps
        if: ${{ steps.setstate.outputs.state != '' }}
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO }}"
          github_token: "${{ secrets.GITHUB }}"
          ado_organization: prism-blue
          ado_project: Azure DevOps Evaluation
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_tags: "Bug,UserStory"
          ado_bypassrules: true
          ado_state: "${{ steps.setstate.outputs.state }}"
          log_level: 100
