name: Sync GitHub Issue to Azure DevOps Work Item

on:
  issues:
    types: [opened, edited, labeled, unlabeled,closed, reopened]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  sync-to-ado:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO }}"
          github_token: "${{ secrets.GITHUB }}"
          ado_organization: prism-blue
          ado_project: Azure DevOps Evaluation
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_tags: "AutoSync"
          ado_bypassrules: true
          log_level: 100
