name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Compose multiple tags
        id: set-tags
        run: |
          echo "ADO_TAGS=Bug;status-${{ github.event.issue.state }}" >> $GITHUB_ENV
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO }}"
          github_token: "${{ secrets.GITHUB }}"
          ado_organization: prism-blue
          ado_project: Azure DevOps Evaluation
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          ado_Add Tag: "${{ env.ADO_TAGS }}"
          log_level: 100
