name: Scheduled Sync to Azure DevOps (Every 1 Min)

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute

concurrency:
  group: issue-scheduler
  cancel-in-progress: false

jobs:
  sync-to-ado:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub Issues to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO }}"
          github_token: "${{ secrets.GITHUB }}"
          ado_organization: prism-blue
          ado_project: Azure DevOps Evaluation
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_ADO tags: "Bug, Auto-Sync"
          ado_bypassrules: true
          log_level: 100
